name: Build Container Image

on:
  workflow_dispatch:
  push:
    paths:
      - Containerfile

jobs:
  build:
    env:
      REGISTRY: ghcr.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set GITHUB_REPO_OWNER and TAG in environment
      run: |
        GITHUB_REPO_OWNER=${{ github.repository_owner }}
        echo "GITHUB_REPO_OWNER=${GITHUB_REPO_OWNER,,}" >> $GITHUB_ENV
        echo "TAGS=${{ env.REGISTRY }}/${GITHUB_REPO_OWNER,,}/fedora-minimal-podman:latest" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push container image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Containerfile
        push: true
        tags: ${{ env.TAGS }}
        
